[project]
name = "datapack_zipper"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "Mav League" }
]
dependencies = [
    "flet>=0.80.3",
    "watchdog"
]

[dependency-groups]
dev = [
    "flet-cli>=0.80.3",
    "flet-desktop>=0.80.3",
    "flet-web>=0.80.3",
]

[tool.flet]
org = "com.mavleague"
product = "datapack_manager"
company = "Mav League"
copyright = "Copyright (C) 2025-2026 by Mav League"

[tool.flet.app]
path = "src"
